export {default as Welcome} from './WelcomePage/Welcome.jsx'
export {default as LoginPage} from './LoginPage/LoginPage.jsx'
export {default as Registration} from './RegistrationPage/Registration.jsx'
export {default as MainPage} from './MainPage/MainPage.jsx'
export {default as ProfilePage} from './ProfilePage/ProfilePage.jsx'