export {default as Login} from './LoginForm/LoginForm.js'
export {default as RegistrationForm} from './RegistrationForm/RegistrationForm.js'
export {default as Input} from './Input/input.jsx'
export {default as Server} from './Server/Server.jsx'
export {default as Modal} from './Modal/Modal.jsx'
export {default as UploadAvatar} from './UploadAvatar/UploadAvatar.jsx'
export {default as Header} from './Header/Header.jsx'